spring:
  application:
    name: SPRING-BOOT_SHOP
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_Toan
    username: root
    password: 27102005Az
  jpa:
    hibernate:
      ddl-auto: update